kind: ConfigMap
metadata:
  name: burrow-config
apiVersion: v1
data:
  burrow.toml: |-
    [zookeeper]
    hostname={{ .Values.zk.host }}
    port={{ .Values.zk.port }}

    [kafka "local"]
    broker={{ .Values.kafka.host }}
    broker-port={{ .Values.kafka.port }}
    zookeeper={{ .Values.zk.host }}
    zookeeper-port={{ .Values.zk.port }}
    zookeeper-path=/
    zookeeper-offsets=true

    [tickers]
    broker-offsets=60

    [lagcheck]
    intervals=10
    expire-group=604800
    min-distance=1
    zookeeper-interval=60
    zk-group-refresh=300

    [httpserver]
    server=on
    port=8080

    [logging]
    level="info"
