kind: ConfigMap
metadata:
  name: burrow-config
apiVersion: v1
data:
  burrow.toml: |-
    [logging]
    level="info"

    [zookeeper]
    servers=[ "{{ .Values.zk.host }}:{{ .Values.zk.port }}" ]
    timeout=10
    root-part="/burrow"

    [client-profile.ft]
    client-id="burrow-ft"
    kafka-version="0.8.2"

    [cluster.local]
    class-name="kafka"
    servers=[ "{{ .Values.kafka.host }}:{{ .Values.kafka.port }}" ]
    client-profile="ft"
    topic-refresh=120
    offset-refresh=30

    [consumer.local_zk]
    class-name="kafka_zk"
    cluster="local"
    servers=[ "{{ .Values.zk.host }}:{{ .Values.zk.port }}" ]
    zookeeper-timeout=30

    [httpserver.default]
    address=":8080"

    [storage.default]
    class-name="inmemory"
    intervals=10
    expire-group=604800
    min-distance=1
