# Default values for burrow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "burrow" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "false"
replicaCount: 1
image:
  name: toddpalino/burrow:1.1.0
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi 
kafka:
  host: "kafka-0.kafka.default.svc.cluster.local"
  port: "9092"
zk:
  host: "kafka-zookeeper"
  port: "2181"
